import { FarmListing } from '../types/farming';

export const INITIAL_FARM_LISTINGS: FarmListing[] = [
  {
    id: 'farm_001',
    sellerId: 'seller_101',
    sellerName: 'Balasaheb Shinde',
    sellerPhone: '+91 98220 84721',
    title: 'Fertile Black Soil Agricultural Land with Perennial Canal & Drip',
    description:
      'Prime 4.5-acre agricultural land located in the rich sugarcane and onion belt of Baramati. Soil is deep Regur (Black Cotton) with 6.5-7.5 pH, ideal for sugarcane, cotton, and vegetables. Features 2 functional borewells (300ft with 2.5-inch constant discharge) plus sanctioned Nira canal irrigation rights. Complete automated drip irrigation lines installed across all plots. 3-phase agricultural power connection with dedicated 15 HP transformer. Direct 25-foot paved road access from state highway.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 4500000, // ₹45 Lakhs (~10 Lakh/acre)
    landSizeAcres: 4.5,
    state: 'Maharashtra',
    district: 'Pune',
    village: 'Baramati Rural (Supa Rd)',
    latitude: 18.1524,
    longitude: 74.5772,
    cropType: 'Sugarcane & Organic Onions',
    soilType: 'Deep Black Cotton Soil (Regur)',
    waterAvailability: 'Canal Rights + 2 High-Yield Borewells (24x7)',
    electricityAvailability: '3-Phase 8 Hours Guaranteed Ag Power',
    roadAccess: '25-ft Paved Approach Road (1 km from State Highway)',
    facilities: [
      '2 Active Borewells',
      'Automated Drip Filtration Unit',
      'Labor Quarters (2 Rooms)',
      'Perimeter Chainlink Fencing',
      'Tractor Shed',
    ],
    status: 'published',
    featured: true,
    createdAt: '2026-09-24T10:30:00.000Z',
    updatedAt: '2026-09-24T10:30:00.000Z',
  },
  {
    id: 'farm_002',
    sellerId: 'seller_102',
    sellerName: 'Sardar Gurvinder Singh',
    sellerPhone: '+91 94172 10988',
    title: 'High-Yield Indo-Gangetic Wheat-Paddy Farm with Tubewell',
    description:
      '8-Acre contiguous flat fertile agricultural holding in Jalandhar fertile plains. Laser-leveled soil with high organic carbon content. Historically yields 24-26 quintals/acre for wheat and 32 quintals/acre for PR-126 Basmati paddy. Powered by heavy-duty 20 HP submersible tubewell with sweet groundwater table. Metal boundary demarcated, clean revenue 7/12 title deeds with zero encumbrance.',
    images: [
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1530507629858-e4977d30e9e0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 9600000, // ₹96 Lakhs (12 Lakh/acre)
    landSizeAcres: 8.0,
    state: 'Punjab',
    district: 'Jalandhar',
    village: 'Nakodar Tehsil',
    latitude: 31.1278,
    longitude: 75.4722,
    cropType: 'Basmati Paddy & Sharbati Wheat',
    soilType: 'Alluvial Loamy Clay',
    waterAvailability: '20 HP Submersible Tubewell + Siphoned Canal Distributary',
    electricityAvailability: 'Dedicated 3-Phase Agricultural Feeder',
    roadAccess: 'Tar Road Frontage suitable for Heavy Combined Harvesters',
    facilities: [
      'Heavy Submersible Motor',
      'Grain Drying Concrete Floor (Khaliyan)',
      'Secure Equipment Godown',
      'Laser Leveled Check Basins',
    ],
    status: 'published',
    featured: true,
    createdAt: '2026-09-22T08:15:00.000Z',
    updatedAt: '2026-09-22T08:15:00.000Z',
  },
  {
    id: 'farm_003',
    sellerId: 'seller_103',
    sellerName: 'Venkata Ramanamurthy',
    sellerPhone: '+91 98481 55670',
    title: 'Certified Organic Red Chilli & Turmeric Farm with Farmhouse',
    description:
      'Scenic 3.2-acre organic certified farm in Guntur district, world-renowned for high capsaicin Guntur Sannam chillies and golden turmeric. Red sandy loam soil enriched with 5 years of Jeevamrutha and green manuring. Contains a modern 1-BHK farmer cottage with solar electricity setup. 1 large open farm pond (30 lakh litre capacity) with polyethylene geomembrane lining, plus 1 functional borewell.',
    images: [
      'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 3800000, // ₹38 Lakhs
    landSizeAcres: 3.2,
    state: 'Andhra Pradesh',
    district: 'Guntur',
    village: 'Tenali Rural',
    latitude: 16.2437,
    longitude: 80.6405,
    cropType: 'Red Chilli, Turmeric & Marigold Border',
    soilType: 'Red Sandy Loam (High Drainage)',
    waterAvailability: 'Lined Farm Pond (30L Capacity) + Borewell 2-inch',
    electricityAvailability: '5 kW Rooftop Solar + Grid Connection',
    roadAccess: '18-ft Metal Road directly connecting to Tenali Bypass',
    facilities: [
      '1-BHK Eco Farmhouse',
      'Solar Pump with Battery Inverter',
      'Micro-Sprinkler Network',
      'Vermicompost Beds (4 units)',
      'Solar Insect Light Traps',
    ],
    status: 'published',
    featured: false,
    createdAt: '2026-09-20T14:45:00.000Z',
    updatedAt: '2026-09-20T14:45:00.000Z',
  },
  {
    id: 'farm_004',
    sellerId: 'seller_104',
    sellerName: 'K. Senthil Nathan',
    sellerPhone: '+91 94433 99812',
    title: 'Mature Coconut & Arecanut Orchard with Drip and Intercropping',
    description:
      '5.0-Acre established horticultural plantation near Pollachi, Coimbatore. Contains 350 bearing high-yielding Pollachi tall coconut palms (yielding ~140 nuts/tree/year) intercropped with nutmeg and black pepper vines on trunks. Soil is rich red loamy with abundant earthworm activity. River Amaravathi sub-basin ground aquifer guarantees uninterrupted sweet water through 2 deep borewells with automatic solar pumps.',
    images: [
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 7500000, // ₹75 Lakhs (15 Lakh/acre)
    landSizeAcres: 5.0,
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    village: 'Pollachi South',
    latitude: 10.6609,
    longitude: 77.0048,
    cropType: 'Pollachi Coconut, Nutmeg & Black Pepper',
    soilType: 'Red Loam with High Organic Matter',
    waterAvailability: '2 Deep Borewells (Sweet Aquifer) + Drip System',
    electricityAvailability: 'Free Tamil Nadu Ag Power Connection (Tariff 4)',
    roadAccess: 'Tar Paved Village Road with Truck Turnaround Space',
    facilities: [
      '350 Bearing Coconut Palms',
      'Copra Drying Yard (1500 sq ft)',
      'Watchman Quarter',
      'Automatic Valve Drip Controllers',
      'Concrete Storage Shed',
    ],
    status: 'published',
    featured: true,
    createdAt: '2026-09-18T11:20:00.000Z',
    updatedAt: '2026-09-18T11:20:00.000Z',
  },
  {
    id: 'farm_005',
    sellerId: 'seller_105',
    sellerName: 'Patel Bhaveshbhai',
    sellerPhone: '+91 98250 14329',
    title: 'Semi-Arid Precision Cotton & Groundnut Land with Micro-Canal',
    description:
      '6.0-Acre fertile agrarian holding in Saurashtra groundnut and cotton corridor. High calcium-rich medium black soil. Equipped with Narmada sub-canal outlet connection and check-dam water storage access. Excellent record of pest-resilient organic cotton and high-oil content groundnut cultivation. Completely fenced with barbed wire on stone posts to prevent wild animal intrusion.',
    images: [
      'https://images.unsplash.com/photo-1598512752271-33f913a5af13?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 5200000, // ₹52 Lakhs
    landSizeAcres: 6.0,
    state: 'Gujarat',
    district: 'Rajkot',
    village: 'Gondal Rural',
    latitude: 21.9619,
    longitude: 70.7937,
    cropType: 'Desi Cotton, Groundnut & Cumin (Jeera)',
    soilType: 'Medium Black Loam (Calcium Rich)',
    waterAvailability: 'Narmada Canal Lift + Sump Reservoir',
    electricityAvailability: 'Gujarat Jyotigram Ag Power (8 Hours)',
    roadAccess: '20-ft WBM Road connecting to NH-27 (2.5 km)',
    facilities: [
      'Full Barbed Wire Fence',
      'Water Sump (1 Lakh Litres)',
      'Diesel Generator Backup',
      'Organic Certification Transfer Ready',
    ],
    status: 'published',
    featured: false,
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-09-15T09:00:00.000Z',
  },
  {
    id: 'farm_006',
    sellerId: 'seller_106',
    sellerName: 'Anand Kumar Gowda',
    sellerPhone: '+91 94801 77201',
    title: 'High-Tech Polyhouse & Open Farm for Exotic Vegetables',
    description:
      '2.2-Acre commercial horticulture facility including 20,000 sq ft climate-controlled naturally ventilated polyhouse. Currently producing English cucumbers and colored bell peppers with direct supply contracts to Bangalore organic supermarkets. Complete foggers, shade nets, and dosatron fertigation injectors installed. Adjacent 1.5 acres open field growing marigold and organic leafy greens.',
    images: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=1200&q=80',
    ],
    price: 6800000, // ₹68 Lakhs
    landSizeAcres: 2.2,
    state: 'Karnataka',
    district: 'Mandya / Mysore Border',
    village: 'Srirangapatna Taluk',
    latitude: 12.4181,
    longitude: 76.6947,
    cropType: 'Bell Peppers (Capsicum), Cucumber & Hydroponic Greens',
    soilType: 'Red Sandy Loam with Coir Pith Enrichment',
    waterAvailability: 'Cauvery Canal Connection + 2 Borewells with RO Unit',
    electricityAvailability: 'Commercial + Ag 3-Phase Continuous Supply',
    roadAccess: 'Tar Road 30-ft Frontage (Direct access to Bangalore-Mysore Highway)',
    facilities: [
      '20,000 sq ft G.I. Pipe Polyhouse',
      'Automated Fogger & Fan Cooling System',
      'Dosatron Fertigation Station',
      'Cold Storage Unit (5 MT Capacity)',
      'Office Room with Wi-Fi Setup',
    ],
    status: 'published',
    featured: true,
    createdAt: '2026-09-12T16:00:00.000Z',
    updatedAt: '2026-09-12T16:00:00.000Z',
  },
];
