import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language, LANGUAGES } from '../types/farming';

const translations: Record<string, Record<string, string>> = {
  en: {
    appTitle: 'AgriSahay',
    appSubtitle: 'SMART ECO-FARMING & DIAGNOSTICS',
    ecoPlan: 'Eco-Plan Generator',
    diseaseDetection: 'Disease Detection',
    compost: 'Compost Planner',
    rotation: 'Crop Rotation',
    journal: 'Farm Journal',
    share: 'Resource Network',
    marketplace: 'Farm Marketplace',
    workspace: 'Schedule & Tasks',
    advisor: 'Bio-Advisor',
    activeSeason: 'Current: Kharif Season',
    footerText: '© {year} AgriSahay. Empowering sustainable regenerative agriculture worldwide.',
    runDiagnosis: 'Run AI Diagnosis',
    diagnosing: 'Diagnosing Crop Health...',
    uploadPrompt: 'Click or drag & drop leaf or crop photo',
    supportsFormats: 'Supports JPG, PNG, WEBP formats (Max 15MB)',
    useSample: 'Or try a sample leaf image:',
    changeImage: 'Change Image',
    scanAnother: 'Scan Another Plant',
    listenAudio: 'Listen to Advisory',
    stopAudio: 'Stop Audio',
    symptoms: 'Observed Symptoms',
    organicRemedies: 'Organic Treatments & Bio-Remedies',
    preventativeMeasures: 'Preventative Cultural Practices',
    spraySchedule: 'Recommended Bio-Spray Schedule',
    confidence: 'AI Confidence',
    category: 'Diagnosis Category',
    severity: 'Severity',
    historyTitle: 'Diagnosis History',
    noHistory: 'No crop diagnoses recorded yet. Upload a leaf photo above.',
    // Eco-Plan
    ecoPlanTitle: 'Custom Regenerative Eco-Plan',
    ecoPlanSubtitle: 'Tailored organic crop recommendations, multi-phase growth roadmaps, water strategies, and market forecasts.',
    locationLabel: 'Farm Location / Region',
    soilTypeLabel: 'Soil Type',
    seasonLabel: 'Current Season',
    farmSizeLabel: 'Farm Size',
    budgetLabel: 'Investment Budget',
    irrigationLabel: 'Irrigation Setup',
    generatePlan: 'Generate Eco-Farming Plan',
    generatingPlan: 'Generating Soil & Crop Plan...',
    sustainabilityScore: 'Eco-Sustainability Score',
    recommendedCropsTitle: 'High-Yield Recommended Organic Crops',
    expectedYield: 'Expected Yield',
    estProfit: 'Est. Net Profit',
    growthTimeline: 'Chronological Organic Growth Plan',
    organicInputs: 'Organic Bio-Inputs',
    waterStrategy: 'Water Conservation Strategy',
    keyPractices: 'Key Regenerative Practices',
    riskTitle: 'Pest & Climate Vulnerability Analysis',
    marketTitle: 'Local Mandi & APMC Market Insights',
    // Compost
    compostTitle: 'Smart Compost & Soil Optimizer',
    compostSubtitle: 'Balance Carbon-to-Nitrogen (C:N) ratios, forecast decomposition timelines, and optimize bio-accelerators.',
    greensTitle: 'Green Materials (Nitrogen Rich)',
    brownsTitle: 'Brown Materials (Carbon Rich)',
    addMaterial: 'Add Material',
    calculateCompost: 'Analyze Compost Balance',
    analyzingCompost: 'Evaluating Compost Chemistry...',
    cnRatio: 'Estimated C:N Ratio',
    readyTime: 'Estimated Ready In',
    readyWeeks: '{weeks} Weeks',
    qualityGrade: 'Bio-Humus Quality Grade',
    accelerators: 'Bio-Accelerators & Microbes',
    // Rotation
    rotationTitle: 'Regenerative Crop Rotation Strategy',
    rotationSubtitle: 'Prevent soil depletion, break pathogen cycles, and boost organic yields through sequential planting.',
    currentCropLabel: 'Current or Last Harvested Crop',
    soilConditionLabel: 'Current Soil Condition',
    targetSeasonLabel: 'Upcoming Target Season',
    generateRotation: 'Generate Rotation Strategy',
    generatingRotation: 'Formulating Crop Succession...',
    nextCrops: 'Recommended Succession Crops',
    intercropping: 'Intercropping & Companion Planting',
    soilRestoration: 'Soil Biology & Health Strategy',
    // Journal
    journalTitle: 'Digital Farm Journal & Operations Log',
    journalSubtitle: 'Track plot activities, organic input applications, harvest yields, and farm economics.',
    addEntry: 'Log New Farm Activity',
    dateLabel: 'Date',
    plotLabel: 'Plot / Field Name',
    activityLabel: 'Activity Description',
    categoryLabel: 'Category',
    inputsUsedLabel: 'Inputs Applied',
    quantityLabel: 'Quantity / Dose',
    harvestLabel: 'Harvest Yield (if any)',
    saveLog: 'Save Journal Entry',
    totalEntries: 'Total Logs',
    totalHarvest: 'Logged Harvest',
    organicDosages: 'Bio-Treatments Recorded',
  },
  hi: {
    appTitle: 'एग्रीसहाय',
    appSubtitle: 'स्मार्ट इको-खेती एवं फसल निदान',
    ecoPlan: 'इको-प्लान जनरेटर',
    diseaseDetection: 'फसल रोग पहचान',
    compost: 'कंपोस्ट योजना',
    rotation: 'फसल चक्र',
    journal: 'फार्म जर्नल',
    advisor: 'जैविक सलाहकार',
    activeSeason: 'वर्तमान: खरीफ मौसम',
    footerText: '© {year} एग्रीसहाय। दुनिया भर में टिकाऊ जैविक कृषि पद्धतियों को बढ़ावा देना।',
    runDiagnosis: 'एआई रोग जांच शुरू करें',
    diagnosing: 'फसल स्वास्थ्य की जांच हो रही है...',
    uploadPrompt: 'पत्ती या फसल की फोटो यहां अपलोड करें',
    supportsFormats: 'JPG, PNG, WEBP (अधिकतम 15MB)',
    useSample: 'या नमूना पत्ती की जांच करें:',
    changeImage: 'फोटो बदलें',
    scanAnother: 'अन्य पौधे की जांच करें',
    listenAudio: 'सलाह सुनें',
    stopAudio: 'आवाज रोकें',
    symptoms: 'देखे गए लक्षण',
    organicRemedies: 'जैविक उपचार और देसी उपाय',
    preventativeMeasures: 'रोकथाम के उपाय',
    spraySchedule: 'जैविक छिड़काव कार्यक्रम',
    confidence: 'एआई सटीकता',
    category: 'श्रेणी',
    severity: 'गंभीरता स्तर',
    historyTitle: 'निदान इतिहास',
    noHistory: 'अभी तक कोई रोग जांच दर्ज नहीं है। ऊपर पत्ती की फोटो अपलोड करें।',
    // Eco-Plan
    ecoPlanTitle: 'कस्टम जैविक इको-प्लान',
    ecoPlanSubtitle: 'मृदा के अनुसार फसल सुझाव, विकास चरण, जल प्रबंधन और मंडी मूल्य अनुमान।',
    locationLabel: 'खेत का स्थान / क्षेत्र',
    soilTypeLabel: 'मिट्टी का प्रकार',
    seasonLabel: 'मौसम',
    farmSizeLabel: 'खेत का आकार',
    budgetLabel: 'लागत बजट',
    irrigationLabel: 'सिंचाई साधन',
    generatePlan: 'इको-प्लान बनाएं',
    generatingPlan: 'जैविक योजना तैयार हो रही है...',
    sustainabilityScore: 'स्थिरता स्कोर',
    recommendedCropsTitle: 'सुझाई गई उच्च-उपज जैविक फसलें',
    expectedYield: 'अनुमानित उपज',
    estProfit: 'अनुमानित शुद्ध लाभ',
    growthTimeline: 'चरणबद्ध जैविक कार्य योजना',
    organicInputs: 'जैविक खाद एवं इनपुट',
    waterStrategy: 'जल संरक्षण रणनीति',
    keyPractices: 'महत्वपूर्ण प्राकृतिक पद्धतियां',
    riskTitle: 'कीट और जलवायु जोखिम विश्लेषण',
    marketTitle: 'मंडी और विपणन अंतर्दृष्टि',
    // Compost
    compostTitle: 'स्मार्ट कंपोस्ट एवं मृदा योजनाकार',
    compostSubtitle: 'कार्बन-नाइट्रोजन (C:N) अनुपात संतुलित करें और गुणवत्ता युक्त जैविक खाद बनाएं।',
    greensTitle: 'हरी सामग्री (नाइट्रोजन युक्त)',
    brownsTitle: 'सूखी/भूरी सामग्री (कार्बन युक्त)',
    addMaterial: 'सामग्री जोड़ें',
    calculateCompost: 'कंपोस्ट विश्लेषण करें',
    analyzingCompost: 'खाद मिश्रण की जांच हो रही है...',
    cnRatio: 'कार्बन-नाइट्रोजन अनुपात',
    readyTime: 'तैयार होने का समय',
    readyWeeks: '{weeks} सप्ताह',
    qualityGrade: 'ह्यूमस गुणवत्ता ग्रेड',
    accelerators: 'जैविक उत्प्रेरक (जीवामृत/छाछ)',
    // Rotation
    rotationTitle: 'प्राकृतिक फसल चक्र रणनीति',
    rotationSubtitle: 'मिट्टी की उर्वरता बनाए रखें, कीटों का चक्र तोड़ें और निरंतर पैदावार लें।',
    currentCropLabel: 'वर्तमान या पिछली फसल',
    soilConditionLabel: 'मिट्टी की वर्तमान स्थिति',
    targetSeasonLabel: 'आगामी मौसम',
    generateRotation: 'फसल चक्र बनाएं',
    generatingRotation: 'फसल चक्र तैयार हो रहा है...',
    nextCrops: 'अनुशंसित अगली फसलें',
    intercropping: 'मिश्रित/सह-फसली खेती के विकल्प',
    soilRestoration: 'मृदा स्वास्थ्य संवर्धन रणनीति',
    // Journal
    journalTitle: 'डिजिटल फार्म जर्नल और कार्य डायरी',
    journalSubtitle: 'खेत की गतिविधियों, जैविक इनपुट, उपज और लाभ का रिकॉर्ड रखें।',
    addEntry: 'नई गतिविधि दर्ज करें',
    dateLabel: 'दिनांक',
    plotLabel: 'खेत / प्लॉट का नाम',
    activityLabel: 'गतिविधि का विवरण',
    categoryLabel: 'श्रेणी',
    inputsUsedLabel: 'प्रयुक्त जैविक इनपुट',
    quantityLabel: 'मात्रा / खुराक',
    harvestLabel: 'प्राप्त उपज',
    saveLog: 'डायरी में सुरक्षित करें',
    totalEntries: 'कुल रिकॉर्ड',
    totalHarvest: 'दर्ज उपज',
    organicDosages: 'जैविक उपचार',
  },
  mr: {
    appTitle: 'अॅग्रीसहाय',
    appSubtitle: 'स्मार्ट इको-शेती व पीक निदान',
    ecoPlan: 'इको-प्लॅन जनरेटर',
    diseaseDetection: 'रोग ओळख',
    compost: 'कंपोस्ट नियोजन',
    rotation: 'पीक फेरपालट',
    journal: 'शेत रोजनिशी',
    advisor: 'सेंद्रिय सल्लागार',
    activeSeason: 'सध्या: खरीप हंगाम',
    footerText: '© {year} अॅग्रीसहाय. शाश्वत व सेंद्रिय शेतीचा प्रसार.',
    runDiagnosis: 'रोग निदान सुरू करा',
    diagnosing: 'पिकाच्या आरोग्याचे विश्लेषण सुरू आहे...',
    uploadPrompt: 'पानांचे किंवा पिकाचे छायाचित्र येथे जोडा',
    supportsFormats: 'JPG, PNG, WEBP (कमाल 15MB)',
    useSample: 'किंवा नमुना छायाचित्र वापरा:',
    changeImage: 'छायाचित्र बदला',
    scanAnother: 'दुसऱ्या झाडाची तपासणी करा',
    listenAudio: 'सल्ला ऐका',
    stopAudio: 'आवाज थांबवा',
    symptoms: 'दिसणारी लक्षणे',
    organicRemedies: 'सेंद्रिय व जैविक उपाय',
    preventativeMeasures: 'प्रतिबंधात्मक उपाय',
    spraySchedule: 'सेंद्रिय फवारणी वेळापत्रक',
    confidence: 'अचूकता',
    category: 'प्रकार',
    severity: 'तीव्रता',
    historyTitle: 'निदान इतिहास',
    noHistory: 'अद्याप कोणतेही रोग निदान नाही. पानाचे छायाचित्र अपलोड करा.',
    ecoPlanTitle: 'सेंद्रिय इको-प्लॅन',
    ecoPlanSubtitle: 'मातीनुसार पीक शिफारसी, वाढीचे टप्पे आणि बाजारभाव अंदाज.',
    locationLabel: 'शेताचे ठिकाण / जिल्हा',
    soilTypeLabel: 'मातीचा प्रकार',
    seasonLabel: 'हंगाम',
    farmSizeLabel: 'क्षेत्रफळ',
    budgetLabel: 'गुंतवणूक बजेट',
    irrigationLabel: 'सिंचन पद्धत',
    generatePlan: 'इको-प्लॅन तयार करा',
    generatingPlan: 'प्लॅन तयार होत आहे...',
    sustainabilityScore: 'पर्यावरण पूरक स्कोअर',
    recommendedCropsTitle: 'शिफारस केलेली पिके',
    expectedYield: 'अपेक्षित उत्पादन',
    estProfit: 'अपेक्षित नफा',
    growthTimeline: 'टप्प्याटप्प्याने सेंद्रिय नियोजन',
    organicInputs: 'सेंद्रिय खते व औषधे',
    waterStrategy: 'पाणी नियोजन',
    keyPractices: 'महत्त्वाच्या सेंद्रिय पद्धती',
    riskTitle: 'कीड व हवामान जोखीम',
    marketTitle: 'बाजारभाव व विक्री संधी',
    compostTitle: 'स्मार्ट कंपोस्ट प्लॅनर',
    compostSubtitle: 'कार्बन-नायट्रोजन प्रमाण संतुलित करून दर्जेदार खत तयार करा.',
    greensTitle: 'हिरवा कचरा (नायट्रोजनयुक्त)',
    brownsTitle: 'सुका कचरा (कार्बनयुक्त)',
    addMaterial: 'घटक जोडा',
    calculateCompost: 'कंपोस्ट विश्लेषण',
    analyzingCompost: 'खताचे विश्लेषण होत आहे...',
    cnRatio: 'C:N प्रमाण',
    readyTime: 'तयार होण्याचा कालावधी',
    readyWeeks: '{weeks} आठवडे',
    qualityGrade: 'खताचा दर्जा',
    accelerators: 'जीवामृत / जैविक घटक',
    rotationTitle: 'पीक फेरपालट पद्धती',
    rotationSubtitle: 'जमिनीची सुपीकता टिकवून ठेवा आणि किडींचे प्रमाण कमी करा.',
    currentCropLabel: 'सध्याचे किंवा मागील पीक',
    soilConditionLabel: 'जमिनीची सध्याची स्थिती',
    targetSeasonLabel: 'पुढील हंगाम',
    generateRotation: 'फेरपालट प्लॅन बनवा',
    generatingRotation: 'प्लॅन तयार होत आहे...',
    nextCrops: 'पुढील पिके',
    intercropping: 'आंतरपिके',
    soilRestoration: 'माती आरोग्य संवर्धन',
    journalTitle: 'शेत रोजनिशी व नोंदी',
    journalSubtitle: 'खतांचा वापर, फवारण्या आणि उत्पन्नाच्या अचूक नोंदी ठेवा.',
    addEntry: 'नवीन नोंद जोडा',
    dateLabel: 'दिनांक',
    plotLabel: 'गट / शेताचे नाव',
    activityLabel: 'कामाचा तपशील',
    categoryLabel: 'प्रवर्ग',
    inputsUsedLabel: 'वापरलेली औषधे/खते',
    quantityLabel: 'प्रमाण',
    harvestLabel: 'उत्पादन',
    saveLog: 'नोंद जतन करा',
    totalEntries: 'एकूण नोंदी',
    totalHarvest: 'नोंदवलेले उत्पादन',
    organicDosages: 'सेंद्रिय फवारण्या',
  },
  te: {
    appTitle: 'అగ్రిసహాయ్',
    appSubtitle: 'స్మార్ట్ ఎకో-వ్యవసాయం & పంట వ్యాధి నిర్ధారణ',
    ecoPlan: 'ఎకో-ప్లాన్ జనరేటర్',
    diseaseDetection: 'వ్యాధి నిర్ధారణ',
    compost: 'కంపోస్ట్ ప్లానర్',
    rotation: 'పంట మార్పిడి',
    journal: 'వ్యవసాయ దినచర్య',
    advisor: 'సేంద్రీయ సలహాదారు',
    activeSeason: 'ప్రస్తుతం: ఖరీఫ్ సీజన్',
    footerText: '© {year} అగ్రిసహాయ్. నిలకడైన వ్యవసాయానికి మద్దతు.',
    runDiagnosis: 'వ్యాధి నిర్ధారణ చేయండి',
    diagnosing: 'పంట ఆరోగ్యాన్ని విశ్లేషిస్తోంది...',
    uploadPrompt: 'ఆకు లేదా పంట ఫోటోను అప్‌లోడ్ చేయండి',
    supportsFormats: 'JPG, PNG, WEBP (గరిష్టంగా 15MB)',
    useSample: 'లేదా నమూనా ఫోటోతో ప్రయత్నించండి:',
    changeImage: 'చిత్రాన్ని మార్చండి',
    scanAnother: 'మరొక మొక్కను తనిఖీ చేయండి',
    listenAudio: 'సలహా వినండి',
    stopAudio: 'ఆపండి',
    symptoms: 'గుర్తించిన లక్షణాలు',
    organicRemedies: 'సేంద్రీయ నివారణ చర్యలు',
    preventativeMeasures: 'ముందస్తు జాగ్రత్తలు',
    spraySchedule: 'పిచికారీ సమయపట్టిక',
    confidence: 'ఖచ్చితత్వం',
    category: 'వర్గం',
    severity: 'తీవ్రత',
    historyTitle: 'చరిత్ర',
    noHistory: 'ఇంతవరకు ఎలాంటి రికార్డులు లేవు.',
    ecoPlanTitle: 'సేంద్రీయ ఎకో-ప్లాన్',
    ecoPlanSubtitle: 'నేల రకం ఆధారంగా పంట సూచనలు, దశలవారీ పెరుగుదల మరియు మార్కెట్ సమాచారం.',
    locationLabel: 'ప్రాంతం',
    soilTypeLabel: 'నేల రకం',
    seasonLabel: 'సీజన్',
    farmSizeLabel: 'విస్తీర్ణం',
    budgetLabel: 'బడ్జెట్',
    irrigationLabel: 'నీటి పారుదల',
    generatePlan: 'ప్లాన్ రూపొందించండి',
    generatingPlan: 'ప్లాన్ సిద్ధమవుతోంది...',
    sustainabilityScore: 'పర్యావరణ స్కోరు',
    recommendedCropsTitle: 'సిఫార్సు చేయబడిన పంటలు',
    expectedYield: 'దిగుబడి అంచనా',
    estProfit: 'నికర లాభం అంచనా',
    growthTimeline: 'సేంద్రీయ పెరుగుదల ప్రణాళిక',
    organicInputs: 'సేంద్రీయ ఎరువులు',
    waterStrategy: 'నీటి సంరక్షణ వ్యూహం',
    keyPractices: 'కీలక పద్ధతులు',
    riskTitle: 'తెగుళ్ళు & వాతావరణ ప్రమాదాలు',
    marketTitle: 'మార్కెట్ విశ్లేషణ',
    compostTitle: 'కంపోస్ట్ ప్లానర్',
    compostSubtitle: 'కార్బన్-నత్రజని సమతుల్యత మరియు నాణ్యమైన కంపోస్ట్ తయారీ.',
    greensTitle: 'ఆకుపచ్చ వ్యర్థాలు (నత్రజని)',
    brownsTitle: 'ఎండు వ్యర్థాలు (కార్బన్)',
    addMaterial: 'పదార్థాన్ని జోడించండి',
    calculateCompost: 'కంపోస్ట్ విశ్లేషణ',
    analyzingCompost: 'విశ్లేషిస్తోంది...',
    cnRatio: 'C:N నిష్పత్తి',
    readyTime: 'సిద్ధమయ్యే సమయం',
    readyWeeks: '{weeks} వారాలు',
    qualityGrade: 'నాణ్యత గ్రేడ్',
    accelerators: 'జీవామృతం & సూక్ష్మజీవులు',
    rotationTitle: 'పంట మార్పిడి వ్యూహం',
    rotationSubtitle: 'నేల సారాన్ని పెంచడానికి మరియు తెగుళ్ళను అరికట్టడానికి క్రమబద్ధమైన పంట మార్పిడి.',
    currentCropLabel: 'ప్రస్తుత లేదా మునుపటి పంట',
    soilConditionLabel: 'నేల పరిస్థితి',
    targetSeasonLabel: 'రాబోయే సీజన్',
    generateRotation: 'మార్పిడి ప్లాన్ సిద్ధం చేయండి',
    generatingRotation: 'రూపొందిస్తోంది...',
    nextCrops: 'తదుపరి పంటలు',
    intercropping: 'అంతర పంటలు',
    soilRestoration: 'నేల ఆరోగ్యం',
    journalTitle: 'వ్యవసాయ డైరీ',
    journalSubtitle: 'పంట పనులు, ఎరువుల వాడకం మరియు దిగుబడి రికార్డులు.',
    addEntry: 'కొత్త వివరాలు నమోదు చేయండి',
    dateLabel: 'తేదీ',
    plotLabel: 'పొలం పేరు',
    activityLabel: 'పని వివరాలు',
    categoryLabel: 'వర్గం',
    inputsUsedLabel: 'వాడిన ఎరువులు/మందులు',
    quantityLabel: 'పరిమాణం',
    harvestLabel: 'దిగుబడి',
    saveLog: 'నమోదు చేయండి',
    totalEntries: 'మొత్తం రికార్డులు',
    totalHarvest: 'నమోదైన దిగుబడి',
    organicDosages: 'సేంద్రీయ పిచికారీలు',
  },
  ta: {
    appTitle: 'அக்ரிசகாய்',
    appSubtitle: 'ஸ்மார்ட் இயற்கை வேளாண்மை & பயிர் நோய் கண்டறிதல்',
    ecoPlan: 'சுற்றுச்சூழல் திட்டம்',
    diseaseDetection: 'பயிர் நோய் கண்டறிதல்',
    compost: 'மக்கும் உரம் திட்டம்',
    rotation: 'பயிர் சுழற்சி',
    journal: 'பண்ணை நாட்குறிப்பு',
    advisor: 'இயற்கை ஆலோசகர்',
    activeSeason: 'தற்போது: குறுவை/பருவம்',
    footerText: '© {year} அக்ரிசகாய். உலகளாவிய நிலையான விவசாய மேம்பாடு.',
    runDiagnosis: 'நோய் பரிசோதனை தொடங்கு',
    diagnosing: 'பயிரின் நலம் பரிசோதிக்கப்படுகிறது...',
    uploadPrompt: 'இலை அல்லது பயிர் புகைப்படத்தை பதிவேற்றவும்',
    supportsFormats: 'JPG, PNG, WEBP (அதிகபட்சம் 15MB)',
    useSample: 'அல்லது மாதிரி புகைப்படத்தை சோதிக்கவும்:',
    changeImage: 'படத்தை மாற்று',
    scanAnother: 'மற்றொரு செடியை சோதிக்கவும்',
    listenAudio: 'ஆலோசனையை கேட்கவும்',
    stopAudio: 'நிறுத்தவும்',
    symptoms: 'கண்டறியப்பட்ட அறிகுறிகள்',
    organicRemedies: 'இயற்கை தீர்வுகள் & மருந்துகள்',
    preventativeMeasures: 'தடுப்பு முறைகள்',
    spraySchedule: 'தெளிக்கும் கால அட்டவணை',
    confidence: 'துல்லியம்',
    category: 'வகை',
    severity: 'தீவிரத்தன்மை',
    historyTitle: 'நோய் கண்டறிதல் வரலாறு',
    noHistory: 'இதுவரை எந்த பதிவும் இல்லை.',
    ecoPlanTitle: 'இயற்கை வேளாண்மை திட்டம்',
    ecoPlanSubtitle: 'மண் மற்றும் பருவநிலைக்கேற்ற இயற்கை பயிர் பரிந்துரைகள்.',
    locationLabel: 'பகுதி / ஊர்',
    soilTypeLabel: 'மண் வகை',
    seasonLabel: 'பருவம்',
    farmSizeLabel: 'நிலப்பரப்பு',
    budgetLabel: 'செலவு வரவு',
    irrigationLabel: 'பாசன முறை',
    generatePlan: 'திட்டம் உருவாக்கு',
    generatingPlan: 'திட்டம் தயாராகிறது...',
    sustainabilityScore: 'சுற்றுச்சூழல் குறியீடு',
    recommendedCropsTitle: 'பரிந்துரைக்கப்பட்ட பயிர்கள்',
    expectedYield: 'எதிர்பார்க்கப்படும் மகசூல்',
    estProfit: 'மதிப்பிடப்பட்ட லாபம்',
    growthTimeline: 'வளர்ச்சி கட்டங்கள்',
    organicInputs: 'இயற்கை உரங்கள்',
    waterStrategy: 'நீர் மேலாண்மை',
    keyPractices: 'முக்கிய வழிமுறைகள்',
    riskTitle: 'பூச்சி & பருவநிலை இடர்கள்',
    marketTitle: 'சந்தை நிலவரம்',
    compostTitle: 'மக்கும் உரம் திட்டமிடல்',
    compostSubtitle: 'கார்பன்-நைட்ரஜன் சமநிலைப்படுத்தி சிறந்த மண்புழு/இயற்கை உரம் தயாரிக்க.',
    greensTitle: 'பச்சை கழிவுகள் (நைட்ரஜன்)',
    brownsTitle: 'உலர்ந்த கழிவுகள் (கார்பன்)',
    addMaterial: 'பொருள் சேர்க்க',
    calculateCompost: 'உர பகுப்பாய்வு',
    analyzingCompost: 'பகுப்பாய்வு நடக்கிறது...',
    cnRatio: 'C:N விகிதம்',
    readyTime: 'தயாராகும் காலம்',
    readyWeeks: '{weeks} வாரங்கள்',
    qualityGrade: 'உர தரம்',
    accelerators: 'ஜீவாமிர்தம் & நுண்ணுயிர்கள்',
    rotationTitle: 'பயிர் சுழற்சி உத்தி',
    rotationSubtitle: 'மண் வளம் பெருக்கவும், பூச்சி சுழற்சியை உடைக்கவும் உகந்த திட்டம்.',
    currentCropLabel: 'தற்போதைய பயிர்',
    soilConditionLabel: 'மண் நிலை',
    targetSeasonLabel: 'அடுத்த பருவம்',
    generateRotation: 'சுழற்சி திட்டம் உருவாக்கு',
    generatingRotation: 'தயாராகிறது...',
    nextCrops: 'அடுத்த பயிர்கள்',
    intercropping: 'ஊடு பயிர் வாய்ப்புகள்',
    soilRestoration: 'மண் ஆரோக்கியம்',
    journalTitle: 'பண்ணை நாட்குறிப்பு',
    journalSubtitle: 'உரங்கள், மருந்து தெளிப்பு மற்றும் மகசூல் பதிவுகள்.',
    addEntry: 'புதிய பதிவு சேர்க்க',
    dateLabel: 'தேதி',
    plotLabel: 'நிலம் / பகுதி',
    activityLabel: 'செயல்பாடு விவரம்',
    categoryLabel: 'வகை',
    inputsUsedLabel: 'பயன்படுத்திய உரம்/மருந்து',
    quantityLabel: 'அளவு',
    harvestLabel: 'மகசூல்',
    saveLog: 'பதிவு செய்',
    totalEntries: 'மொத்த பதிவுகள்',
    totalHarvest: 'பதிவான மகசூல்',
    organicDosages: 'இயற்கை மருந்துகள்',
  },
  pa: {
    appTitle: 'ਐਗਰੀਸਹਾਏ',
    appSubtitle: 'ਸਮਾਰਟ ਕੁਦਰਤੀ ਖੇਤੀ ਅਤੇ ਫ਼ਸਲ ਨਿਦਾਨ',
    ecoPlan: 'ਇਕੋ-ਪਲਾਨ ਜਨਰੇਟਰ',
    diseaseDetection: 'ਫ਼ਸਲ ਬਿਮਾਰੀ ਜਾਂਚ',
    compost: 'ਕੰਪੋਸਟ ਯੋਜਨਾ',
    rotation: 'ਫ਼ਸਲੀ ਚੱਕਰ',
    journal: 'ਖੇਤ ਡਾਇਰੀ',
    advisor: 'ਕੁਦਰਤੀ ਸਲਾਹਕਾਰ',
    activeSeason: 'ਮੌਜੂਦਾ: ਸਾਉਣੀ ਸੀਜ਼ਨ',
    footerText: '© {year} ਐਗਰੀਸਹਾਏ। ਕੁਦਰਤੀ ਤੇ ਟਿਕਾਊ ਖੇਤੀ ਨੂੰ ਸਮਰਪਿਤ।',
    runDiagnosis: 'ਬਿਮਾਰੀ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ',
    diagnosing: 'ਫ਼ਸਲ ਦੀ ਸਿਹਤ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
    uploadPrompt: 'ਪੱਤੇ ਜਾਂ ਫ਼ਸਲ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ',
    supportsFormats: 'JPG, PNG, WEBP (ਵੱਧ ਤੋਂ ਵੱਧ 15MB)',
    useSample: 'ਜਾਂ ਨਮੂਨਾ ਫੋਟੋ ਵਰਤੋ:',
    changeImage: 'ਤਸਵੀਰ ਬਦਲੋ',
    scanAnother: 'ਦੂਜੇ ਬੂਟੇ ਦੀ ਜਾਂਚ ਕਰੋ',
    listenAudio: 'ਸਲਾਹ ਸੁਣੋ',
    stopAudio: 'ਰੋਕੋ',
    symptoms: 'ਵੇਖੇ ਗਏ ਲੱਛਣ',
    organicRemedies: 'ਦੇਸੀ ਅਤੇ ਜੈਵਿਕ ਹੱਲ',
    preventativeMeasures: 'ਰੋਕਥਾਮ ਦੇ ਉਪਾਅ',
    spraySchedule: 'ਜੈਵਿਕ ਸਪਰੇਅ ਸਮਾਂ-ਸਾਰਣੀ',
    confidence: 'ਸ਼ੁੱਧਤਾ',
    category: 'ਸ਼੍ਰੇਣੀ',
    severity: 'ਗੰਭੀਰਤਾ',
    historyTitle: 'ਜਾਂਚ ਇਤਿਹਾਸ',
    noHistory: 'ਅਜੇ ਕੋਈ ਜਾਂਚ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ। ਉੱਪਰ ਪੱਤੇ ਦੀ ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ।',
    ecoPlanTitle: 'ਕੁਦਰਤੀ ਇਕੋ-ਪਲਾਨ',
    ecoPlanSubtitle: 'ਜ਼ਮੀਨ ਮੁਤਾਬਕ ਫ਼ਸਲ ਚੋਣ, ਪਾਣੀ ਪ੍ਰਬੰਧ ਅਤੇ ਮੰਡੀ ਭਾਅ ਅਨੁਮਾਨ।',
    locationLabel: 'ਖੇਤ ਦਾ ਇਲਾਕਾ / ਜ਼ਿਲ੍ਹਾ',
    soilTypeLabel: 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    seasonLabel: 'ਮੌਸਮ / ਸੀਜ਼ਨ',
    farmSizeLabel: 'ਖੇਤ ਦਾ ਆਕਾਰ',
    budgetLabel: 'ਲਾਗਤ ਬਜਟ',
    irrigationLabel: 'ਸਿੰਚਾਈ ਸਾਧਨ',
    generatePlan: 'ਇਕੋ-ਪਲਾਨ ਬਣਾਓ',
    generatingPlan: 'ਪਲਾਨ ਤਿਆਰ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    sustainabilityScore: 'ਵਾਤਾਵਰਣ ਸਕੋਰ',
    recommendedCropsTitle: 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਫ਼ਸਲਾਂ',
    expectedYield: 'ਸੰਭਾਵਿਤ ਝਾੜ',
    estProfit: 'ਸੰਭਾਵਿਤ ਸ਼ੁੱਧ ਮੁਨਾਫ਼ਾ',
    growthTimeline: 'ਪੜਾਅਵਾਰ ਜੈਵਿਕ ਕਾਰਜ ਯੋਜਨਾ',
    organicInputs: 'ਦੇਸੀ ਖਾਦਾਂ ਤੇ ਕੀਟਨਾਸ਼ਕ',
    waterStrategy: 'ਪਾਣੀ ਬਚਾਓ ਨੀਤੀ',
    keyPractices: 'ਜ਼ਰੂਰੀ ਕੁਦਰਤੀ ਤਰੀਕੇ',
    riskTitle: 'ਕੀੜੇ ਅਤੇ ਮੌਸਮੀ ਜੋਖਮ',
    marketTitle: 'ਮੰਡੀ ਅੰਕੜੇ ਤੇ ਰੁਝਾਨ',
    compostTitle: 'ਕੰਪੋਸਟ ਤੇ ਮਿੱਟੀ ਯੋਜਨਾਕਾਰ',
    compostSubtitle: 'ਕਾਰਬਨ-ਨਾਈਟ੍ਰੋਜਨ ਅਨੁਪਾਤ ਸੰਤੁਲਿਤ ਕਰਕੇ ਉੱਤਮ ਰੂੜੀ/ਖਾਦ ਤਿਆਰ ਕਰੋ।',
    greensTitle: 'ਹਰਾ ਕਚਰਾ (ਨਾਈਟ੍ਰੋਜਨ ਭਰਪੂਰ)',
    brownsTitle: 'ਸੁੱਕਾ ਕਚਰਾ (ਕਾਰਬਨ ਭਰਪੂਰ)',
    addMaterial: 'ਸਮੱਗਰੀ ਸ਼ਾਮਲ ਕਰੋ',
    calculateCompost: 'ਕੰਪੋਸਟ ਜਾਂਚ ਕਰੋ',
    analyzingCompost: 'ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
    cnRatio: 'C:N ਅਨੁਪਾਤ',
    readyTime: 'ਤਿਆਰ ਹੋਣ ਦਾ ਸਮਾਂ',
    readyWeeks: '{weeks} ਹਫ਼ਤੇ',
    qualityGrade: 'ਖਾਦ ਦਾ ਗ੍ਰੇਡ',
    accelerators: 'ਜੀਵਾਮ੍ਰਿਤ / ਲੱਸੀ / ਗੁੜ ਦਾ ਘੋਲ',
    rotationTitle: 'ਫ਼ਸਲੀ ਚੱਕਰ ਯੋਜਨਾ',
    rotationSubtitle: 'ਮਿੱਟੀ ਦੀ ਉਪਜਾਊ ਸ਼ਕਤੀ ਬਣਾਈ ਰੱਖਣ ਅਤੇ ਬਿਮਾਰੀਆਂ ਰੋਕਣ ਲਈ ਫ਼ਸਲ ਬਦਲ ਕੇ ਬੀਜੋ।',
    currentCropLabel: 'ਮੌਜੂਦਾ ਜਾਂ ਪਿਛਲੀ ਫ਼ਸਲ',
    soilConditionLabel: 'ਜ਼ਮੀਨ ਦੀ ਹਾਲਤ',
    targetSeasonLabel: 'ਅਗਲਾ ਸੀਜ਼ਨ',
    generateRotation: 'ਫ਼ਸਲੀ ਚੱਕਰ ਬਣਾਓ',
    generatingRotation: 'ਚੱਕਰ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ...',
    nextCrops: 'ਅਗਲੀਆਂ ਫ਼ਸਲਾਂ',
    intercropping: 'ਰਲਵੀਂ ਖੇਤੀ ਦੇ ਵਿਕਲਪ',
    soilRestoration: 'ਮਿੱਟੀ ਸੁਧਾਰ ਰਣਨੀਤੀ',
    journalTitle: 'ਖੇਤ ਡਾਇਰੀ ਅਤੇ ਕੰਮ ਰਿਕਾਰਡ',
    journalSubtitle: 'ਦੇਸੀ ਖਾਦਾਂ, ਸਪਰੇਆਂ ਅਤੇ ਝਾੜ ਦਾ ਪੂਰਾ ਹਿਸਾਬ ਰੱਖੋ।',
    addEntry: 'ਨਵਾਂ ਕੰਮ ਦਰਜ ਕਰੋ',
    dateLabel: 'ਮਿਤੀ',
    plotLabel: 'ਖੇਤ / ਟੱਕ ਦਾ ਨਾਂ',
    activityLabel: 'ਕੰਮ ਦਾ ਵੇਰਵਾ',
    categoryLabel: 'ਸ਼੍ਰੇਣੀ',
    inputsUsedLabel: 'ਵਰਤੀ ਗਈ ਖਾਦ/ਸਪਰੇਅ',
    quantityLabel: 'ਮਾਤਰਾ',
    harvestLabel: 'ਕੁੱਲ ਝਾੜ',
    saveLog: 'ਡਾਇਰੀ ਵਿੱਚ ਦਰਜ ਕਰੋ',
    totalEntries: 'ਕੁੱਲ ਰਿਕਾਰਡ',
    totalHarvest: 'ਦਰਜ ਝਾੜ',
    organicDosages: 'ਜੈਵਿਕ ਸਪਰੇਆਂ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('agrisahay_lang');
    if (saved) {
      const found = LANGUAGES.find((l) => l.code === saved);
      if (found) return found;
    }
    return LANGUAGES[0];
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('agrisahay_lang', lang.code);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language.code]?.[key] || translations['en']?.[key] || key;
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(params[paramKey]));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
